name: solarapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/eco_lightbulb.jpg
    - assets/images/solar_worker.jpg
    - assets/images/solarconn.jpg
    - assets/images/solarconndetails.jpg
    - assets/images/slide1.jpg
    - assets/images/slide2.jpg
    - assets/images/slide3.jpg
    - assets/images/slide4.jpg
    - assets/images/installer1.jpg
    - assets/images/installer2.jpg
    - assets/images/installer3.jpg
