// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBECGU9l5JBNrqIYHctTnxB1r2sqMCj6GA',
    appId: '1:428339605589:web:41e226138118cf130664dc',
    messagingSenderId: '428339605589',
    projectId: 'solarapp-1e8ca',
    authDomain: 'solarapp-1e8ca.firebaseapp.com',
    storageBucket: 'solarapp-1e8ca.firebasestorage.app',
    measurementId: 'G-12NX0EBCDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXsWr3WiUm8lmEzjULvu1a9Ly6pnYizYs',
    appId: '1:428339605589:android:12e05e4e233b49bb0664dc',
    messagingSenderId: '428339605589',
    projectId: 'solarapp-1e8ca',
    storageBucket: 'solarapp-1e8ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcwpDSruVwxg-Quc5ks8pTKjmjgI5uvpk',
    appId: '1:428339605589:ios:3386adc32cfef6640664dc',
    messagingSenderId: '428339605589',
    projectId: 'solarapp-1e8ca',
    storageBucket: 'solarapp-1e8ca.firebasestorage.app',
    iosBundleId: 'com.example.solarapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcwpDSruVwxg-Quc5ks8pTKjmjgI5uvpk',
    appId: '1:428339605589:ios:3386adc32cfef6640664dc',
    messagingSenderId: '428339605589',
    projectId: 'solarapp-1e8ca',
    storageBucket: 'solarapp-1e8ca.firebasestorage.app',
    iosBundleId: 'com.example.solarapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBECGU9l5JBNrqIYHctTnxB1r2sqMCj6GA',
    appId: '1:428339605589:web:59a2353d33f4d0f10664dc',
    messagingSenderId: '428339605589',
    projectId: 'solarapp-1e8ca',
    authDomain: 'solarapp-1e8ca.firebaseapp.com',
    storageBucket: 'solarapp-1e8ca.firebasestorage.app',
    measurementId: 'G-D21W1M9N6W',
  );
}
